services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"

  keycloak-db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      - sqlserver
    entrypoint:
      - /bin/bash
      - -c
      - |
        until /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P Your_password123 -C -Q "SELECT 1"; do
          echo "Waiting for SQL Server..."
          sleep 2
        done
        /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P Your_password123 -C -Q "IF DB_ID(N'KeycloakDb') IS NULL CREATE DATABASE [KeycloakDb];"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_DB: mssql
      KC_DB_URL: "jdbc:sqlserver://sqlserver:1433;databaseName=KeycloakDb;encrypt=false;trustServerCertificate=true"
      KC_DB_USERNAME: sa
      KC_DB_PASSWORD: "Your_password123"
      KC_TRANSACTION_XA_ENABLED: "false"
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import:ro
    depends_on:
      keycloak-db-init:
        condition: service_completed_successfully

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "5341:80"

  api:
    build:
      context: .
      dockerfile: src/Fcg.Identity.WebApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      - sqlserver
      - kafka
      - seq
    ports:
      - "8080:8080"
