apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: identity-runtime
  namespace: fcs-identity
spec:
  infisicalAuthRef:
    name: fcs-platform-auth
    namespace: infisical-operator-system
  syncOptions:
    refreshInterval: 5m
    instantUpdates: false
  sources:
    - projectSlug: fcs-platform-dd-uk
      environmentSlug: prod
      secretPath: /platform
  targets:
    - name: identity-runtime
      namespace: fcs-identity
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          ConnectionStrings__SqlServer: 'Server=sqlserver-service.fcs-infra.svc.cluster.local,1433;Database=IdentityDb;User Id=sa;Password={{ secretFrom "/platform" "sql-sa-password" }};Encrypt=False;TrustServerCertificate=True'
          Keycloak__AdminPassword: '{{ secretFrom "/platform" "keycloak-admin-password" }}'
          ManagerSeed__Password: '{{ secretFrom "/platform" "manager-password" }}'
