apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fcs-identity-api
  namespace: fcs-identity
spec:
  ingressClassName: fcs-traefik
  tls:
    - hosts:
        - fcs-identity.flaviojcf.com.br
      secretName: fcs-identity-tls
  rules:
    - host: fcs-identity.flaviojcf.com.br
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: fcs-identity-service
                port:
                  number: 8080
