name: Fcs.Identity CI

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  checks: write
  security-events: write
  packages: write

jobs:
  ci:
    uses: group10-tc-01/fcs-pipelines/.github/workflows/dotnet-service-ci.yml@main
    with:
      service_name: fcs-identity
      dotnet_version: 10.0.x
      solution_path: Fcs.Identity.slnx
      unit_tests_path: tests/Fcs.Identity.UnitTests/Fcs.Identity.UnitTests.csproj
      integration_tests_path: tests/Fcs.Identity.IntegratedTests/Fcs.Identity.IntegratedTests.csproj
      functional_tests_path: tests/Fcs.Identity.FunctionalTests/Fcs.Identity.FunctionalTests.csproj
      test_environment: Test
      coverage_threshold: 80
      run_sonar: true
      sonar_project_key: group10-tc-01_fcs-identity
      sonar_organization: group10-tc-01
      dockerfile_path: src/Fcs.Identity.WebApi/Dockerfile
      docker_context: .
    secrets: inherit
